
version: 2

models:
  - name: stg_order
    description: "A staging table for the raw order_table in DB"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  
  - name: stg_category
    description: "A staging table for the raw category_table in DB"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_product
    description: "A staging table for the raw product_table in DB"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_supplier
    description: "A staging table for the raw supplier_table in DB"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_customer
    description: "A staging table for the seeded sd_customer file in the seeds folder"
    columns:
      - name: customerID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_shipper
    description: "A staging table for the seeded sd_shipper file in the seeds folder"
    columns:
      - name: shipperID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_employee
    description: "A staging table for the seeded sd_employee file in the seeds folder"
    columns:
      - name: shipperID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null